[build-system]
requires = [
    "robotpy-build>=2020.0.8,<2021.0.0",
    "wpilib>=2020.1.2"
]

[tool.robotpy-build]
base_package = "rev"

[tool.robotpy-build.wrappers."rev".maven_lib_download]
artifact_id = "SparkMax-cpp"
group_id = "com.revrobotics.frc"
repo_url = "http://www.revrobotics.com/content/sw/max/sdk/maven"
version = "1.5.1"

libs = ["SparkMax"]


[tool.robotpy-build.wrappers."rev"]
name = "rev"

generate = [
    { CANAnalog = "rev/CANAnalog.h" },
    { CANDeviceScanner = "rev/CANDeviceScanner.h" },
    { CANDigitalInput = "rev/CANDigitalInput.h" },
    { CANEncoder = "rev/CANEncoder.h" },
    { CANError = "rev/CANError.h" },
    { CANPIDController = "rev/CANPIDController.h" },
    { CANSensor = "rev/CANSensor.h" },
    { CANSparkMax = "rev/CANSparkMax.h" },
    # { CANSparkMaxLowLevel = "rev/CANSparkMaxLowLevel.h" },
    { ControlType = "rev/ControlType.h" },
    { SparkMax = "rev/SparkMax.h" },
]

generation_data = "gen"

[tool.robotpy-build.metadata]
name = "robotpy-rev"
description = "Rev Robotics Spark Max SDK for RobotPy"
author = "RobotPy Development Team"
author_email = "robotpy@googlegroups.com"
url = "https://github.com/robotpy/robotpy-rev"
license = "BSD-3-Clause"
install_requires = []